spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/biot_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

