spring:
  jackson:
    time-zone: UTC

  datasource:
    url: jdbc:postgresql://localhost:5432/biot_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: ${TIMEZONE_IDENTIFIER}

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/biot_db
    user: postgres
    password: postgres
    locations: classpath:db/migration
    default-schema: public
    repair-on-migrate: true

logging:
  level:
    org.flywaydb: DEBUG'

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /v3/api-docs

jwt:
  secret: ${JWT_SECRET:K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=}
  expiration: 86400000

timezone:
  identifier: ${TIMEZONE_IDENTIFIER}