ALTER TABLE device      ALTER COLUMN created_at  TYPE TIMESTAMPTZ;
ALTER TABLE sensor_data ALTER COLUMN created_at  TYPE TIMESTAMPTZ;
ALTER TABLE control_log ALTER COLUMN created_at  TYPE TIMESTAMPTZ;
ALTER TABLE alert_log   ALTER COLUMN created_at  TYPE TIMESTAMPTZ;
ALTER TABLE room_device ALTER COLUMN updated_at  TYPE TIMESTAMPTZ;
